### ISSUE TITLE
failed to achieve the declared Fscore in the paper

### ISSUE THREAD

**Issue by cherylzhao** [csJd/deep_exhaustive#1]
I'm learning something about nested NER and glad to find your implementation in pytorch.May I ask how much does your model achieve in terms of Fscore?I got 68%.I'm afraid that there is something wrong when I run the code.
Thanks.

**Comment by csJd** [comment]
I requested the code and data from the authors, but no reply.
My re-implemented version got about 71% in terms of F-score, but I cannot found any problem according to their paper.
You can point it out if you could find any issue of my re-implemented version, thank you.
